name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOTNET_VERSION: '9.0.x' # or '8.0.x' if you prefer
  NUGET_SOURCE: 'https://api.nuget.org/v3/index.json'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x  
            8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test (if you have tests)
        run: dotnet test --no-build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./artifacts

      - name: Publish to NuGet
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}